##pmacct (Promiscuous mode IP Accounting package)
##pmacct is Copyright (C) 2003-2020 by Paolo Lucente

#Author: Marc Sune <marcdevel (at) gmail.com>

#This Dockerfile creates an image for pmbmpd 

#The pmacct daemon is ran with a non-root user (required for being 
#able to locally run the test-framework as a non-root user)

FROM base:_build
MAINTAINER pmacct Docker Doctors <docker-doctors (at) pmacct.net>

# Set UID 1000 for the pmacct process
RUN useradd -m -u 1000 -o -s /bin/bash pmacct_user
USER pmacct_user

ENTRYPOINT ["/usr/local/sbin/pmbmpd"]
CMD ["-f", "/etc/pmacct/pmbmpd.conf"]
